# Generated by Django 4.2.15 on 2024-08-20 19:56

from django.db import migrations, models


def remove_duplicates(apps, schema_editor):

    PartialDigest = apps.get_model('django_digest', 'PartialDigest')  # noqa
    duplicates = (
        PartialDigest.objects
        .values('login')
        .annotate(count_id=models.Count('id'))
        .filter(count_id__gt=1)
    )

    # Delete every duplicate, but keep last entry in DB
    for duplicate in duplicates:
        PartialDigest.objects.filter(login=duplicate['login']).exclude(
            id=PartialDigest.objects.filter(login=duplicate['login'])
            .order_by()
            .last()
            .id
        ).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('django_digest', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, noop),
        migrations.AddConstraint(
            model_name='partialdigest',
            constraint=models.UniqueConstraint(
                fields=('login', 'confirmed'), name='unique_login_with_confirm'
            ),
        ),
    ]
